# Generated by Django 6.0.5 on 2026-05-14 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', '⏳ En attente'), ('confirmee', '✅ Confirmée'), ('en_cours', '📖 En cours'), ('terminee', '🏁 Terminée'), ('annulee', '❌ Annulée')], default='en_attente', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_retour_effectif', models.DateField(blank=True, null=True)),
                ('penalite', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='livres.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
            },
        ),
    ]
