# Generated by Django 6.0.5 on 2026-05-14 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(default='📚', max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('annee_publication', models.IntegerField(blank=True, null=True)),
                ('editeur', models.CharField(blank=True, max_length=150)),
                ('nombre_exemplaires', models.PositiveIntegerField(default=1)),
                ('prix_location_jour', models.DecimalField(decimal_places=2, default=5.0, max_digits=8)),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='livres.categorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
