# Generated by Django 6.0.5 on 2026-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
